version: 2
updates:
  # Enable version updates for Flutter dependencies
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - namdq
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
