// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFG6EtXscMNn8k1CsbiEx299lKVun_Nhc',
    appId: '1:58790249044:web:0bc7698783d53bc9fc63c1',
    messagingSenderId: '58790249044',
    projectId: 'ecommerceapp-3dcfd',
    authDomain: 'ecommerceapp-3dcfd.firebaseapp.com',
    storageBucket: 'ecommerceapp-3dcfd.firebasestorage.app',
    measurementId: 'G-795WQ8R2Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdlyihrgu8nosXzrRptFmrgVznfxTAgc',
    appId: '1:58790249044:android:ca9bf98e3daa57bdfc63c1',
    messagingSenderId: '58790249044',
    projectId: 'ecommerceapp-3dcfd',
    storageBucket: 'ecommerceapp-3dcfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP0dZGc29rM3kQYfSeJAXBu5YZdssv1P8',
    appId: '1:58790249044:ios:cf42437ee9dc609cfc63c1',
    messagingSenderId: '58790249044',
    projectId: 'ecommerceapp-3dcfd',
    storageBucket: 'ecommerceapp-3dcfd.firebasestorage.app',
    androidClientId: '58790249044-uoabu1tn64b5l01un7v2r184ovtep9m7.apps.googleusercontent.com',
    iosClientId: '58790249044-sef9nrchtscbmqu7v8gjhf2r79qae7n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}