name: Build APK & IPA

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest
    name: Build Android APK

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-release
          path: build/app/outputs/apk/release/

  build_ios:
    runs-on: macos-latest
    name: Build iOS IPA

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd build/ios/Release-iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r -q ../../../build/app/outputs/ipa/app-release.ipa Payload
          cd ../../../

      - name: Upload IPA artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: build/app/outputs/ipa/

  build_web:
    runs-on: ubuntu-latest
    name: Build Web

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: build/web/
